### ISSUE TITLE
ESLint warning in shallowCopy.js

### ISSUE THREAD

**Issue by 025f779e** [BME-MIT-IET/teammutable-iet-2019#1]
ESLint reports: "16:3  warning  for..in loops iterate over the entire prototype chain, which is virtually never what you want. Use Object.{keys,values,entries}, and iterate over the resulting array".

shallowCopy should be rewritten to use Object.assign. hasOwnProperty.js should be removed if it becomes unused.

**Comment by Dyromic** [comment]
Reopen if somebody figured out why the Object.assign() failed in tests.

**Comment by Dyromic** [comment]
If someone figured out why Object.assign failed then reopen this issue.
