### ISSUE TITLE
ESLint no-prototype-builtins warnings

### ISSUE THREAD

**Issue by 025f779e** [BME-MIT-IET/teammutable-iet-2019#2]
In src/Record.js 121:26 and src/utils/isArrayLike.js 23:15, hasOwnProperty is called directly on an object. This can fail in some circumstances, so Object.prototype.hasOwnProperty.call should be used instead.

**Comment by Dyromic** [comment]
Much safer approach: works with null reference.

**Comment by Dyromic** [comment]
Changes merged to master.
