### ISSUE TITLE
ESLint use rest parameters instead of 'arguments'

### ISSUE THREAD

**Issue by 025f779e** [BME-MIT-IET/teammutable-iet-2019#3]
Some methods (e.g. Set.of) use the arguments object, while others (e.g. Set.union) use more modern rest parameters. Everything should use rest parameters.

Full list of occurences:
[prefer-rest-params.txt](https://github.com/BME-MIT-IET/teammutable-iet-2019/files/3144923/prefer-rest-params.txt)

**Comment by Dyromic** [comment]
Much modern solution for parameter packs.
