### ISSUE TITLE
ESLint warning in functions returning empty containers

### ISSUE THREAD

**Issue by 025f779e** [BME-MIT-IET/teammutable-iet-2019#4]
Several containers have functions like the following:
`let EMPTY_STACK;
function emptyStack() {
  return EMPTY_STACK || (EMPTY_STACK = makeStack(0));
}`
These generate a "Return statement should not contain assignment" warning. Consider rewriting them like this:
`let EMPTY_STACK = makeStack(0);
function emptyStack() {
  return EMPTY_STACK;
}`
Full list of occurences:
[no-return-assign.txt](https://github.com/BME-MIT-IET/teammutable-iet-2019/files/3144943/no-return-assign.txt)

**Comment by Dyromic** [comment]
The builds failed because you don't run the "npm run test" command, but it works as expected.
