### ISSUE TITLE
Manual code review

### ISSUE THREAD

**Issue by 025f779e** [BME-MIT-IET/teammutable-iet-2019#8]
The code should be reviewed manually to see if we can find issues that atomated static analysis does not.

**Comment by Dyromic** [comment]
I will review the functional/ and methods/ folder's content.

**Comment by mate0515** [comment]
I'll watch on predicates/ and utils/

**Comment by mate0515** [comment]
Haven't found any problems

**Comment by Dyromic** [comment]
There are some code duplications like typeof x === 'function' would be nice to replace with a function call.

**Comment by oszika05** [comment]
I reviewed the root folder, and fixed some style issues.

**Comment by Dyromic** [comment]
Reopen if somebody found a way to increase code quality.
